server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    gzip on;
    gzip_types text/plain application/xml text/css application/javascript;
    gzip_proxied any;
    gzip_min_length  1000;
    gzip_disable "MSIE [1-6]\.";

    # CSS and Javascript
    location ~* \.(?:css|js)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "max-age=15778476, public";
    }

    # Media: images, icons, video, audio, HTC
    location /assets/* {
        expires 1M;
        access_log off;
        # max-age must be in seconds
        add_header Cache-Control "max-age=2629746, public";
    }


    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page  400 401 403 404 500 502 503 504  /404.html;
    location = /404.html {
        root   /usr/share/nginx/html;
    }
}
