images:
  roundel: https://raw.githubusercontent.com/cs-soc-tudublin/IdentityFlip/master/assets/logos/cspp.svg
  emote: https://raw.githubusercontent.com/cs-soc-tudublin/IdentityFlip/master/assets/logos/resign-emote.png
society:
  name: CS++
  tagline: TU Dublin's Computer Science Society.
navigation:
  global:
    - text: Blog
      link: /blog/posts/stealing-from-redbrick.html
  blog:
    - text: Events
      tag: events
    - text: Admin Blog
      tag: admins
    - text: Tutorials
      tag: tutorial
    - text: Conferences
      tag: conferences
    - text: Newsletters
      tag: newsletter
  buttons:
    primary:
      text: Sign Up!
      link: https://join.cspp.ie
    secondary:
      text: Discord
      link: https://discord.cspp.ie
drawer: navigation
home:
  hero:
    title:
      secondary: TU Dublin's Computer Science Society.
      primary: Join us today!
    body: CS++ was restarted in 2022 with a goal to aid its members - today, we help our members with their coursework, and give them access to invaluable experiences and skills!
    buttons:
      primary:
        text: Sign Up!
        link: https://join.cspp.ie
      secondary:
        text: Discord
        link: https://discord.cspp.ie
  cta:
    title: Don't Miss Out!
    body: CS++ runs events of all kinds, provides discounted tickets to conferences, and helps you academically.
    button:
      text: Sign Up Today!
      link: https://join.cspp.ie/
  committee:
    - name: Faith Omotayo
      position: 🪑 Chair
      username: chillingwithmani
      image: /assets/img/committee/faith.webp
    - name: David Corcoran
      position: 🪑 Vice-Chair
      username: Arcane
      image: /assets/img/committee/david.webp
    - name: Bohdan Yeriemienko
      position: 💌 Secretary
      username: bog
      image: /assets/img/committee/bohdan.webp
    - name: Adrian Mae
      position: 💸 Treasurer
      username: thatikeashark
      image: /assets/img/committee/adrian.webp
    - name: Nikita Aksenov
      position: 📢 PRO
      image: /assets/img/committee/nikita.webp
      username: nawinds
    - name: Juliet Mullarney
      position: 👩‍⚕️ HSO
      username: juliet
      image: /assets/img/committee/juliet.webp
    - name: Ana
      position: 📅 Technical Events Officer
      username: ana_rchy
      image: /assets/img/committee/ana.gif
    - name: Ethan Crosbie
      position: 📅 Social Events Officer
      username: ethan
      image: /assets/img/committee/ethan.webp
    - name: Derv O'Flynn
      position: 🚀 SysAdmin
      username: BigCheeseDerv
      image: /assets/img/committee/derv.webp
    - name: MJ
      position: 🚀 SysAdmin
      username: DroolingFeralHog
      image: /assets/img/committee/mj.webp
    - name: Jacey
      position: 🚀 SysAdmin
      username: sokomuso
      image: /assets/img/committee/jacey.webp
    - name: Ruán Murgatroyd
      position: 🚀 SysAdmin
      username: rjm
      image: /assets/img/committee/ruan.webp
footer:
  credit: Created from Redbrick's Atlas System