images:
  roundel: https://raw.githubusercontent.com/cs-soc-tudublin/IdentityFlip/master/assets/logos/cspp.svg
  emote: https://raw.githubusercontent.com/cs-soc-tudublin/IdentityFlip/master/assets/logos/resign-emote.png
society:
  name: CS++
  tagline: TU Dublin's Computer Science Society.
navigation:
  global:
    - text: Open Governance
      link: /open-governance/readme.html
    - text: Blog
      link: /blog/posts/2024-01-31-redbrick-maintenance-with-nomad.html
  blog:
    - text: Events
      tag: events
    - text: Admin Blog
      tag: admins
    - text: Tutorials
      tag: tutorial
    - text: Conferences
      tag: conferences
    - text: Newsletters
      tag: newsletter
  buttons:
    primary:
      text: Signup
      link: https://join.cspp.ie
    secondary:
      text: Discord
      link: https://discord.cspp.ie
drawer: navigation
home:
  hero:
    title:
      secondary: TU Dublin's Computer Science Society.
      primary: Join us today!
    body: CS++ was restarted in 2022 with a goal to aid its members - today, we help our members with their coursework, and give them access to invaluable experiences and skills!
    buttons:
      primary:
        text: Signup
        link: https://join.cspp.ie
      secondary:
        text: Discord
        link: https://discord.cspp.ie
  cta:
    title: Don't Miss Out!
    body: CS++ runs events of all kinds, provides discounted tickets, and helps you academically.
    button:
      text: Signup
      link: https://join.cspp.ie/
  committee:
    - name: Faith Omotayo
      position: 🪑 Chair
      username: chillingwithmani
      image: /assets/img/committee/faith.webp
    - name: David Corcoran
      position: 🪑 Vice-Chair
      username: rcayn
      image: /assets/img/committee/pluto.jpg
    - name: Bohdan Yeriemienko
      position: 💌 Secretary
      username: bog8998
      image: /assets/img/committee/cheese.png
    - name: Adrian Capacite
      position: 💸 Treasurer
      username: nairdah
      image: /assets/img/committee/calcifer.png
    - name: Nikita Aksenov
      position: 📢 PRO
      image: /assets/img/committee/payne.png
      username: nawinds
    - name: Juliet Mullarney
      position: 👩‍⚕️ HSO
      username: juuliet4715
      image: /assets/img/committee/payne.png
    - name: Ana
      position: 📅 Technical Events Officer
      username: ana_rchy
      image: /assets/img/committee/ana.gif
    - name: Ethan Crosbie
      position: 📅 Social Events Officer
      username: ethan_everel
      image: /assets/img/committee/stefania.jpg
    - name: Derv O'Flynn
      position: 🚀 SysAdmin
      username: kit_fisto
      image: /assets/img/committee/cathalog.jpg
    - name: MJ Moore
      position: 🚀 SysAdmin
      username: geansaidor
      image: /assets/img/committee/hypnoant.png
    - name: Jacey Janczak
      position: 🚀 SysAdmin
      username: sokomuso
      image: /assets/img/committee/hypnoant.png
    - name: Ruán Murgatroyd
      position: 🚀 SysAdmin
      username: irishtnt
      image: /assets/img/committee/ruan.webp
footer:
  credit: Created from Redbrick's Atlas System