images:
  roundel: https://raw.githubusercontent.com/cs-soc-tudublin/IdentityFlip/master/assets/logos/cspp.svg
  embed: https://raw.githubusercontent.com/cs-soc-tudublin/IdentityFlip/master/assets/logos/roundel.png
society:
  name: CS++
  tagline: TU Dublin's Computer Science Society.
navigation:
  global:
    - text: Blog
      link: /blog/posts/using-sonarqube.html
  blog:
    - text: Events
      tag: events
    - text: Admin Blog
      tag: admins
    - text: Tutorials
      tag: tutorial
    - text: Conferences
      tag: conferences
    - text: Newsletters
      tag: newsletter
  buttons:
    primary:
      text: Sign Up!
      link: https://join.cspp.ie
    secondary:
      text: Discord
      link: https://discord.cspp.ie
drawer: navigation
home:
  hero:
    title:
      secondary: TU Dublin's Computer Science Society.
      primary: Join us today!
    body: CS++ was restarted in 2022 with a goal to aid its members - today, we help our members with their coursework, and give them access to invaluable experiences and skills!
    buttons:
      primary:
        text: Sign Up!
        link: https://join.cspp.ie
        aria: Link to the Clubs and Socs portal to join the society!
      secondary:
        link: https://instagram.com/tudublincsplusplus
        aria: Link to our Instagram page!
      tertiary:
        link: https://discord.cspp.ie
        aria: Link to our Discord server!
  cta:
    title: Don't Miss Out!
    body: CS++ runs events of all kinds, provides discounted tickets to conferences, and helps you academically.
    button:
      text: Sign Up Today!
      link: https://join.cspp.ie/
  committee:
    - name: Faith Omotayo
      position: 🪑 Chair
      username: chillingwithmani
      image: /assets/img/committee/faith.webp
    - name: David Corcoran
      position: 🪑 Vice-Chair
      username: Arcane
      image: /assets/img/committee/david.webp
    - name: Bohdan Yeriemienko
      position: 💌 Secretary
      username: bohdan
      image: /assets/img/committee/bohdan.webp
    - name: Mae Capacite
      position: 💸 Treasurer
      username: maeyonaise.jar
      image: /assets/img/committee/mae.webp
    - name: Sayo Owolabi
      position: 📢 PRO
      username: kejiayan
      image: /assets/img/committee/sayo.webp
    - name: Juliet Mullarney
      position: 👩‍⚕️ HSO
      username: juliet
      image: /assets/img/committee/juliet.webp
    - name: Ana
      position: 💻 Tech Events Officer
      username: ana_rchy
      image: /assets/img/committee/ana.gif
    - name: Ethan Crosbie
      position: 🥳 Social Events Officer
      username: ethan
      image: /assets/img/committee/ethan.webp
    - name: Derv O'Flynn
      position: 🚀 SysAdmin
      username: BigCheeseDerv
      image: /assets/img/committee/derv.webp
    - name: MJ
      position: 🚀 SysAdmin
      username: DroolingFeralHog
      image: /assets/img/committee/mj.webp
    - name: Jacey
      position: 🚀 SysAdmin
      username: sokomuso
      image: /assets/img/committee/jacey.webp
    - name: Ruán Murgatroyd
      position: 🚀 SysAdmin
      username: rjm
      image: /assets/img/committee/ruan.webp
    - name: Eman Abdelatti
      position: 🗓️ Events Rep
      username: Emmy24
      image: /assets/img/committee/eman.webp
    - name: Lívia Guimarães
      position: 👼 First Year Rep
      username: livguimaraes
      image: /assets/img/committee/liv.webp
    - name: Damisola Talabi
      position: 😅 Second Year Rep
      username: Damisola_74125
      image: /assets/img/committee/dami.webp
  sponsorSection:
    enquiryStart: Want to be part of something great?
    enquiryEnd: Get in touch!
    enquiryLink: mailto:comp@societies.tudublin.ie?subject=Sponsorship Inquiry
  sponsors:
    - name: Accenture
      image: /assets/img/sponsors/accenture.png
      link: https://accenture.com/ie-en
      tier: Primary Sponsor
      weight: bold
      colour: primary
    - name: Rewriting the Code
      image: /assets/img/sponsors/rtc.webp
      link: https://rewritingthecode.org/
      tier: General Sponsor
      weight: normal
      colour: normal

footer:
  credit: Powered by Redbrick's Atlas System
