images:
  roundel: https://raw.githubusercontent.com/cs-soc-tudublin/IdentityFlip/master/assets/logos/cspp.svg
  emote: https://raw.githubusercontent.com/cs-soc-tudublin/IdentityFlip/master/assets/logos/resign-emote.png
society:
  name: CS++
  tagline: TU Dublin's Computer Science Society.
navigation:
  global:
    - text: Blog
      link: /blog/posts/writing-clerk.html
  blog:
    - text: Events
      tag: events
    - text: Admin Blog
      tag: admins
    - text: Tutorials
      tag: tutorial
    - text: Conferences
      tag: conferences
    - text: Newsletters
      tag: newsletter
  buttons:
    primary:
      text: Sign Up!
      link: https://join.cspp.ie
    secondary:
      text: Discord
      link: https://discord.cspp.ie
drawer: navigation
home:
  hero:
    title:
      secondary: TU Dublin's Computer Science Society.
      primary: Join us today!
    body: CS++ was restarted in 2022 with a goal to aid its members - today, we help our members with their coursework, and give them access to invaluable experiences and skills!
    buttons:
      primary:
        text: Sign Up!
        link: https://join.cspp.ie
      secondary:
        link: https://linkedingram.com/tudublincsplusplus
      tertiary:
        link: https://discord.cspp.ie
  cta:
    title: Don't Miss Out!
    body: CS++ runs events of all kinds, provides discounted tickets to conferences, and helps you academically.
    button:
      text: Sign Up Today!
      link: https://join.cspp.ie/
  committee:
    - name: Faith Omotayo
      position: 🪑 Chair
      username: chillingwithmani
      image: /assets/img/committee/faith.webp
      bio:
        line1: none
        line2: none
        line3: none
        line4: none
      linkedin: none
      github: none
    - name: David Corcoran
      position: 🪑 Vice-Chair
      username: Arcane
      image: /assets/img/committee/david.webp
      bio:
        line1: none
        line2: none
        line3: none
        line4: none
      linkedin: none
      github: none
    - name: Bohdan Yeriemienko
      position: 💌 Secretary
      username: bog
      image: /assets/img/committee/bohdan.webp
      bio:
        line1: none
        line2: none
        line3: none
        line4: none
      linkedin: none
      github: none
    - name: Adrian Mae
      position: 💸 Treasurer
      username: thatikeashark
      image: /assets/img/committee/adrian.webp
      bio:
        line1: none
        line2: none
        line3: none
        line4: none
      linkedin: none
      github: none
    - name: Nikita Aksenov
      position: 📢 PRO
      image: /assets/img/committee/nikita.webp
      bio:
        line1: none
        line2: none
        line3: none
        line4: none
      linkedin: none
      github: none
      username: nawinds
    - name: Juliet Mullarney
      position: 👩‍⚕️ HSO
      username: juliet
      image: /assets/img/committee/juliet.webp
      bio:
        line1: none
        line2: none
        line3: none
        line4: none
      linkedin: none
      github: none
    - name: Ana
      position: 💻 Tech Events Officer
      username: ana_rchy
      image: /assets/img/committee/ana.gif
      bio:
        line1: none
        line2: none
        line3: none
        line4: none
      linkedin: none
      github: none
    - name: Ethan Crosbie
      position: 🥳 Social Events Officer
      username: ethan
      image: /assets/img/committee/ethan.webp
      bio:
        line1: none
        line2: none
        line3: none
        line4: none
      linkedin: none
      github: none
    - name: Derv O'Flynn
      position: 🚀 SysAdmin
      username: BigCheeseDerv
      image: /assets/img/committee/derv.webp
      bio:
        line1: none
        line2: none
        line3: none
        line4: none
      linkedin: none
      github: none
    - name: MJ
      position: 🚀 SysAdmin
      username: DroolingFeralHog
      image: /assets/img/committee/mj.webp
      bio:
        line1: none
        line2: none
        line3: none
        line4: none
      linkedin: none
      github: none
    - name: Jacey
      position: 🚀 SysAdmin
      username: sokomuso
      image: /assets/img/committee/jacey.webp
      bio:
        line1: none
        line2: none
        line3: none
        line4: none
      linkedin: none
      github: none
    - name: Ruán Murgatroyd
      position: 🚀 SysAdmin
      username: rjm
      image: /assets/img/committee/ruan.webp
      bio:
        line1: Hello!
        line2: I'm Ruán, a sysadmin for CS++. I'm in 3rd year studying Computer Science (International).
        line3: I started in CS++ in 2022, became chair in 2023, and transitioned to sysadmin in 2024 to focus on the technical stack.
        line4: I've developed BitHunt, WebFelt, and am the Webmaster for CS++.<br>I love programming, system administration and learning how things work!<br>You can find me on LinkedIn and GitHub above, or chat to me on campus!
      linkedin: https://www.linkedin.com/in/ruan-murgatroyd/
      github: https://github.com/RJMurg/
footer:
  credit: Created from Redbrick's Atlas System
