images:
  roundel: https://raw.githubusercontent.com/cs-soc-tudublin/IdentityFlip/master/assets/logos/cspp.svg
  embed: https://raw.githubusercontent.com/cs-soc-tudublin/IdentityFlip/master/assets/logos/roundel.png
society:
  name: CS++
  tagline: TU Dublin's Computer Science Society.
navigation:
  global:
    - text: Blog
      link: /blog/posts/using-sonarqube.html
  blog:
    - text: Events
      tag: events
    - text: Admin Blog
      tag: admins
    - text: Tutorials
      tag: tutorial
    - text: Conferences
      tag: conferences
    - text: Newsletters
      tag: newsletter
  buttons:
    primary:
      text: Sign Up!
      link: https://join.cspp.ie
    secondary:
      text: Discord
      link: https://discord.cspp.ie
drawer: navigation
home:
  hero:
    title:
      secondary: TU Dublin's Computer Science Society.
      primary: Join us today!
    body: CS++ got its name in 2022, and traces its history back to 1998 with one goal; to aid its members - today, we help our members with their coursework, and give them access to invaluable experiences and skills!
    buttons:
      primary:
        text: Sign Up!
        link: https://join.cspp.ie
        aria: Link to the Clubs and Socs portal to join the society!
      secondary:
        link: https://instagram.com/tudublincsplusplus
        aria: Link to our Instagram page!
      tertiary:
        link: https://discord.cspp.ie
        aria: Link to our Discord server!
  cta:
    title: Don't Miss Out!
    body: CS++ runs events of all kinds, provides discounted tickets to conferences, and helps you academically.
    button:
      text: Sign Up Today!
      link: https://join.cspp.ie/
  committee:
    - name: Lívia Guimarães
      position: 🪑 Chair
      username: livguimaraes
      image: ./assets/img/committee/liv.webp
    - name: Faith Omotayo
      position: 🪑 Vice-Chair
      username: faithomotayo
      image: ./assets/img/committee/faith.webp
    - name: Anmool Shah
      position: 💌 Secretary
      username: anmool
      image: ./assets/img/committee/anmool.webp
    - name: It could be you!
      position: 💸 Treasurer
      username: joinUs
      image: ./assets/img/committee/unknown.webp
    - name: It could be you!
      position: 📢 PRO
      username: joinUs
      image: ./assets/img/committee/unknown.webp
    - name: Eman Abdelatti
      position: 👩‍⚕️ HSO
      username: Emmy24
      image: ./assets/img/committee/eman.webp
    - name: It could be you!
      position: 💻 Tech Events Officer
      username: joinUs
      image: ./assets/img/committee/unknown.webp
    - name: Bohdan Yeriemienko
      position: 🥳 Social Events Officer
      username: bohdan
      image: ./assets/img/committee/bohdan.webp
    - name: Daniel Smyth
      position: 🚀 SysAdmin
      username: rockerkemm
      image: ./assets/img/committee/dan.webp
    - name: D O'Flynn
      position: 🚀 SysAdmin
      username: BigCheese
      image: ./assets/img/committee/derv.webp
    - name: MJ
      position: 🚀 SysAdmin
      username: mjm
      image: ./assets/img/committee/mj.webp
    - name: Ruán Murgatroyd
      position: 🚀 SysAdmin
      username: rjm
      image: ./assets/img/committee/ruan.webp
    - name: Tyler Brady
      position: 🚀 SysAdmin
      username: relyT
      image: ./assets/img/committee/tyler.webp
    - name: It could be you!
      position: 🗓️ Events Rep
      username: joinUs
      image: ./assets/img/committee/unknown.webp
    - name: It could be you!
      position: 👼 First Year Rep
      username: joinUs
      image: ./assets/img/committee/unknown.webp
    - name: It could be you!
      position: 😅 Second Year Rep
      username: joinUs
      image: ./assets/img/committee/unknown.webp
  sponsorSection:
    enquiryStart: Want to be part of something great?
    enquiryEnd: Get in touch!
    enquiryLink: mailto:comp@societies.tudublin.ie?subject=Sponsorship Inquiry
  sponsors:
    - name: Rewriting the Code
      image: ./assets/img/sponsors/rtc.webp
      link: https://rewritingthecode.org/
      tier: General Sponsor
      weight: normal
      colour: normal

footer:
  credit: Powered by Redbrick's Atlas System
