name: Spellcheck Action
on: 
    pull_request:
        branches:
            - 'dev'
            - 'main'

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.43.0
      name: Spellcheck
      with:
        config_path: "spellcheckConfig.yml"
